name: cddpm
channels:
  - pytorch
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - accelerate=0.32.1
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.11.6
  - aiosignal=1.3.1
  - aom=3.5.0
  - appdirs=1.4.4
  - async-timeout=5.0.1
  - attrs=24.2.0
  - aws-c-auth=0.7.11
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.12
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.4.1
  - aws-c-http=0.8.0
  - aws-c-io=0.14.0
  - aws-c-mqtt=0.10.1
  - aws-c-s3=0.4.9
  - aws-c-sdkutils=0.1.13
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.26.0
  - aws-sdk-cpp=1.11.210
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.3
  - ca-certificates=2024.9.24
  - cairo=1.18.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cmake=3.30.1
  - colorama=0.4.6
  - contourpy=1.3.0
  - cpython=3.9.20
  - cycler=0.12.1
  - dataclasses=0.8
  - datasets=2.14.4
  - dav1d=1.2.1
  - dill=0.3.7
  - distro=1.9.0
  - docker-pycreds=0.4.0
  - eigen=3.4.0
  - expat=2.6.3
  - ffmpeg=6.0.0
  - fftw=3.3.10
  - filelock=3.16.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - fsspec=2024.10.0
  - gdk-pixbuf=2.42.12
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glib=2.82.2
  - glib-tools=2.82.2
  - glog=0.6.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.8
  - graphite2=1.3.14
  - harfbuzz=8.5.0
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.7
  - importlib-metadata=8.5.0
  - importlib-resources=6.4.5
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.5
  - jasper=4.2.4
  - jinja2=3.1.4
  - joblib=1.4.2
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - leptonica=1.83.1
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.3
  - libarchive=3.7.4
  - libarrow=15.0.0
  - libarrow-acero=15.0.0
  - libarrow-dataset=15.0.0
  - libarrow-flight=15.0.0
  - libarrow-flight-sql=15.0.0
  - libarrow-gandiva=15.0.0
  - libarrow-substrait=15.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.8.0
  - libcxx=19.1.4
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.3
  - libffi=3.4.4
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.82.2
  - libgoogle-cloud=2.12.0
  - libgrpc=1.59.3
  - libhwloc=2.11.1
  - libiconv=1.17
  - libidn2=2.3.3
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libitk=5.4.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libnghttp2=1.58.0
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopencv=4.8.1
  - libopenvino=2023.1.0
  - libopenvino-arm-cpu-plugin=2023.1.0
  - libopenvino-auto-batch-plugin=2023.1.0
  - libopenvino-auto-plugin=2023.1.0
  - libopenvino-hetero-plugin=2023.1.0
  - libopenvino-ir-frontend=2023.1.0
  - libopenvino-onnx-frontend=2023.1.0
  - libopenvino-paddle-frontend=2023.1.0
  - libopenvino-pytorch-frontend=2023.1.0
  - libopenvino-tensorflow-frontend=2023.1.0
  - libopenvino-tensorflow-lite-frontend=2023.1.0
  - libopus=1.3.1
  - libparquet=15.0.0
  - libpng=1.6.44
  - libprotobuf=4.24.4
  - libre2-11=2023.09.01
  - librsvg=2.54.4
  - libsqlite=3.47.0
  - libssh2=1.11.0
  - libtasn1=4.19.0
  - libtheora=1.1.1
  - libthrift=0.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuv=1.49.2
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=19.1.4
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - lzo=2.10
  - make=4.4.1
  - markupsafe=3.0.2
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.15
  - munkres=1.1.4
  - ncurses=6.5
  - nettle=3.8.1
  - networkx=3.2.1
  - ninja=1.12.1
  - nomkl=1.0
  - numba=0.60.0
  - numpy=1.24.3
  - numpy-base=1.24.3
  - opencv=4.8.1
  - openh264=2.3.1
  - openjpeg=2.5.2
  - openssl=3.4.0
  - orc=1.9.2
  - p11-kit=0.24.1
  - packaging=24.2
  - pandas=2.1.1
  - pango=1.50.14
  - pathtools=0.1.2
  - pcre2=10.44
  - pillow=11.0.0
  - pip=23.3.2
  - pixman=0.43.4
  - propcache=0.2.0
  - psutil=6.1.0
  - pthread-stubs=0.4
  - pugixml=1.14
  - py-opencv=4.8.1
  - pyarrow=15.0.0
  - pycparser=2.22
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.9.20
  - python-dateutil=2.9.0.post0
  - python-tzdata=2024.2
  - python-xxhash=3.5.0
  - python_abi=3.9
  - pytorch=2.1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - re2=2023.09.01
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - rhash=1.4.5
  - sacremoses=0.0.53
  - safetensors=0.4.5
  - scikit-build=0.17.6
  - scikit-learn=1.3.2
  - scipy=1.11.3
  - sentry-sdk=2.18.0
  - setproctitle=1.3.4
  - setuptools=75.1.0
  - simpleitk=2.4.0
  - six=1.16.0
  - sleef=3.7
  - smmap=5.0.0
  - snappy=1.1.10
  - sqlite=3.47.0
  - svt-av1=1.7.0
  - sympy=1.13.3
  - tbb=2021.13.0
  - tesseract=5.4.1
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tomli=2.1.0
  - torchaudio=2.1.0
  - torchvision=0.16.0
  - tornado=6.4.1
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wheel=0.44.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.2
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.17.2
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - antlr4-python3-runtime==4.9.3
      - colorlog==6.9.0
      - deprecated==1.2.15
      - einops==0.7.0
      - einops-exts==0.0.4
      - ema-pytorch==0.7.3
      - grpcio==1.68.0
      - huggingface-hub==0.26.2
      - humanize==4.11.0
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - imageio==2.36.0
      - lazy-loader==0.4
      - lightning-utilities==0.11.9
      - markdown==3.7
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - monai==1.3.0
      - natsort==8.4.0
      - nibabel==5.3.2
      - omegaconf==2.3.0
      - platformdirs==4.3.6
      - protobuf==3.20.1
      - pydeprecate==0.3.2
      - pygments==2.18.0
      - python-dotenv==1.0.0
      - pytorch-lightning==1.6.5
      - rich==13.6.0
      - scikit-image==0.24.0
      - shellingham==1.5.4
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tifffile==2024.8.30
      - timm==0.6.12
      - tokenizers==0.20.3
      - torchio==0.20.2
      - torchmetrics==1.2.0
      - tqdm==4.66.1
      - transformers==4.46.3
      - typer==0.13.1
      - wandb==0.18.7
      - werkzeug==3.1.3
      - wrapt==1.16.0
