name: cddpm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core Python and PyTorch setup with specific versions
  - python=3.9
  - setuptools=59.5.0
  - pip=21.2.4
  - tensorboard=2.7.0

  # Scientific computing
  - numpy==1.22.4
  - pandas=1.3.4
  - scipy=1.7.2
  - scikit-learn=1.0.1
  - scikit-image=0.18.3
  - h5py=3.6.0
  - nibabel=3.2.1
  
  # Visualization
  - matplotlib=3.5.2
  - seaborn=0.11.2

  - pip:
    - accelerate==0.7.1
    - albumentations==1.1.0
    - ants==0.0.7
    - antspyx==0.5.4
    - clip==0.2.0
    - einops==0.4.1
    - einops_exts==0.0.3
    - ema_pytorch==0.0.8
    - grad_cam==1.3.7
    - hydra-core==1.1.0
    - hydra-colorlog==1.1.0
    - imageio==2.10.3
    - kornia==0.6.7
    - monai==1.0.1
    - natsort==8.2.0
    - numba==0.54.0
    - omegaconf==2.1.2
    - opencv_python==4.5.4.60
    - Pillow==9.4.0
    - python-dotenv==0.21.1
    - pytorch-ignite==0.4.7
    - pytorch-lightning==1.5.1
    - pytorch-ranger==0.1.1
    - torch-optimizer==0.3.0
    - torch-tb-profiler==0.3.1
    - torchinfo==1.6.5
    - torchio>=0.18.90,<0.19.0
    - torchmetrics==0.8.0
    # # - torchsampler==0.1.1
    # - pytorch-ignite==0.4.11    # was 0.4.7
    # - pytorch-lightning==1.8.6   # was 1.5.1
    # - pytorch-ranger==0.1.1     # can stay the same
    # - torch-optimizer==0.3.0    # can stay the same
    # - torch-tb-profiler==0.4.0  # was 0.3.1
    # - torchinfo==1.6.5         # can stay the same
    # - torchio==0.18.73         # can stay the same
    # - torchmetrics==0.8.0      # can stay the same
    - torchsampler==0.1.1     
    - torchxrayvision==0.0.32
    - PyYAML==6.0
    - requests==2.26.0
    - rich==13.3.1
    - rotary_embedding_torch==0.1.5
    - SimpleITK==2.2.1
    - timm==0.6.7
    - tqdm==4.62.3
    - transformers==4.26.1
    - ttach==0.0.3
    - video_diffusion_pytorch==0.5.3
    # - wandb==0.12.19
    - wandb>=0.18.7
